services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    restart: unless-stopped

  app:
    build: .
    container_name: rag_app
    volumes:
      - .:/workspace
    depends_on:
      - ollama
      - chromadb
    environment:
      # - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CHROMA_HOST=http://chromadb:8000
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /workspace
    command: tail -f /dev/null

  # jupyter:
  #   image: python:3.11-slim
  #   container_name: jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - .:/home/jovyan/work
  #   command: >
  #     bash -c "pip install --no-cache-dir notebook pandas numpy matplotlib && jupyter lab --ip=0.0.0.0 --port=8888 --allow-root"

  # jupyter:
  #   image: jupyter/scipy-notebook:latest
  #   container_name: jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - .:/home/jovyan/work
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   restart: unless-stopped

volumes:
  ollama_data: